name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Install dependencies
        run: |
          go get github.com/gruntwork-io/terratest/modules/terraform
          go get github.com/gruntwork-io/terratest/modules/aws
          go get github.com/stretchr/testify/assert 

      - name: Run Terratest
        run: |
          go mod init terraform
          go test -v test/s3_test.go
